/* tslint:disable */
// generated by typescript-json-validator
import Ajv = require('ajv');
import {Margins, Page, FontAliases, Grid, Opt, FieldBase, TextField, HtmlField, SvgField, TableCell, TableField, Field, BasePage, MessageText, Messages, ConsciousnessMap, Column, BgColours, Candle, Section, ChartPage, PageName, LayoutConfig} from './layoutTypes';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":true,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {Margins, Page, FontAliases, Grid, Opt, FieldBase, TextField, HtmlField, SvgField, TableCell, TableField, Field, BasePage, MessageText, Messages, ConsciousnessMap, Column, BgColours, Candle, Section, ChartPage, PageName, LayoutConfig};
export const Schema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "BasePage": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "background": {
          "type": "string"
        },
        "fields": {
          "items": {
            "anyOf": [
              {
                "$ref": "#/definitions/Partial<TextField>_1"
              },
              {
                "$ref": "#/definitions/Partial<HtmlField>_1"
              },
              {
                "$ref": "#/definitions/Partial<SvgField>"
              },
              {
                "$ref": "#/definitions/Partial<TableField>"
              }
            ]
          },
          "type": "array"
        },
        "grid": {
          "$ref": "#/definitions/Partial"
        }
      },
      "required": [
        "background",
        "fields"
      ],
      "type": "object"
    },
    "BgColours": {
      "additionalProperties": {
        "type": "string"
      },
      "defaultProperties": [
      ],
      "type": "object"
    },
    "Candle": {
      "$ref": "#/definitions/Candle_1"
    },
    "Candle_1": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "high": {
          "type": "number"
        },
        "highRows": {
          "type": "number"
        },
        "low": {
          "type": "number"
        },
        "lowRows": {
          "type": "number"
        },
        "mid": {
          "type": "number"
        }
      },
      "required": [
        "high",
        "highRows",
        "low",
        "lowRows",
        "mid"
      ],
      "type": "object"
    },
    "ChartPage": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "background": {
          "type": "string"
        },
        "col1": {
          "$ref": "#/definitions/Column"
        },
        "col2": {
          "$ref": "#/definitions/Column"
        },
        "consciousness_map": {
          "$ref": "#/definitions/ConsciousnessMap"
        },
        "fields": {
          "items": {
            "anyOf": [
              {
                "$ref": "#/definitions/Partial<TextField>_1"
              },
              {
                "$ref": "#/definitions/Partial<HtmlField>_1"
              },
              {
                "$ref": "#/definitions/Partial<SvgField>"
              },
              {
                "$ref": "#/definitions/Partial<TableField>"
              }
            ]
          },
          "type": "array"
        },
        "grid": {
          "$ref": "#/definitions/Partial"
        },
        "message_groups": {
          "items": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "type": "array"
        },
        "messages": {
          "$ref": "#/definitions/Messages"
        },
        "sections": {
          "items": {
            "$ref": "#/definitions/Partial<Section>"
          },
          "type": "array"
        }
      },
      "required": [
        "background",
        "col1",
        "col2",
        "consciousness_map",
        "fields",
        "message_groups",
        "messages",
        "sections"
      ],
      "type": "object"
    },
    "Column": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "bottom": {
          "type": "number"
        },
        "left": {
          "type": "number"
        },
        "row_height": {
          "type": "number"
        },
        "top": {
          "type": "number"
        },
        "width": {
          "type": "number"
        }
      },
      "required": [
        "left",
        "width"
      ],
      "type": "object"
    },
    "ConsciousnessMap": {
      "additionalProperties": {
        "additionalProperties": false,
        "defaultProperties": [
        ],
        "properties": {
          "displayName": {
            "type": "string"
          },
          "value": {
            "type": "number"
          }
        },
        "required": [
          "displayName",
          "value"
        ],
        "type": "object"
      },
      "defaultProperties": [
      ],
      "type": "object"
    },
    "Field": {
      "anyOf": [
        {
          "$ref": "#/definitions/TextField"
        },
        {
          "$ref": "#/definitions/HtmlField"
        },
        {
          "$ref": "#/definitions/SvgField"
        },
        {
          "$ref": "#/definitions/TableField"
        }
      ]
    },
    "FieldBase": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "align": {
          "type": "string"
        },
        "caption": {
          "type": [
            "null",
            "string"
          ]
        },
        "captionFont": {
          "type": "string"
        },
        "captionSize": {
          "type": "number"
        },
        "font": {
          "type": "string"
        },
        "fontSize": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "opt": {
          "$ref": "#/definitions/Opt"
        },
        "radius": {
          "type": "number"
        },
        "text": {
          "type": "string"
        },
        "width": {
          "type": "number"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        }
      },
      "required": [
        "caption",
        "captionFont",
        "captionSize",
        "font",
        "fontSize",
        "height",
        "name",
        "radius",
        "text",
        "width",
        "x",
        "y"
      ],
      "type": "object"
    },
    "FontAliases": {
      "additionalProperties": {
        "type": "string"
      },
      "defaultProperties": [
      ],
      "type": "object"
    },
    "Grid": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "height": {
          "type": [
            "null",
            "number"
          ]
        },
        "left": {
          "type": "number"
        },
        "show": {
          "type": "boolean"
        },
        "space": {
          "type": "number"
        },
        "top": {
          "type": "number"
        },
        "width": {
          "type": [
            "null",
            "number"
          ]
        }
      },
      "required": [
        "height",
        "left",
        "show",
        "space",
        "top",
        "width"
      ],
      "type": "object"
    },
    "HtmlField": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "align": {
          "type": "string"
        },
        "caption": {
          "type": [
            "null",
            "string"
          ]
        },
        "captionFont": {
          "type": "string"
        },
        "captionSize": {
          "type": "number"
        },
        "font": {
          "type": "string"
        },
        "fontSize": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "opt": {
          "$ref": "#/definitions/Opt"
        },
        "radius": {
          "type": "number"
        },
        "text": {
          "type": "string"
        },
        "type": {
          "enum": [
            "html"
          ],
          "type": "string"
        },
        "width": {
          "type": "number"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        }
      },
      "required": [
        "caption",
        "captionFont",
        "captionSize",
        "font",
        "fontSize",
        "height",
        "name",
        "radius",
        "text",
        "type",
        "width",
        "x",
        "y"
      ],
      "type": "object"
    },
    "LayoutConfig": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "blank_chart_meows": {
          "$ref": "#/definitions/BasePage"
        },
        "blank_chart_news2": {
          "$ref": "#/definitions/BasePage"
        },
        "cover_page": {
          "$ref": "#/definitions/BasePage"
        },
        "font_aliases": {
          "$ref": "#/definitions/FontAliases"
        },
        "fonts": {
          "additionalProperties": {
            "type": "string"
          },
          "defaultProperties": [
          ],
          "type": "object"
        },
        "meows": {
          "$ref": "#/definitions/ChartPage"
        },
        "news2": {
          "$ref": "#/definitions/ChartPage"
        },
        "page": {
          "$ref": "#/definitions/Page"
        },
        "pages_back_meows": {
          "items": {
            "enum": [
              "blank_chart_meows",
              "blank_chart_news2",
              "cover_page",
              "meows",
              "news2",
              "threshold_4cols",
              "threshold_5cols"
            ],
            "type": "string"
          },
          "type": "array"
        },
        "pages_back_news2": {
          "items": {
            "enum": [
              "blank_chart_meows",
              "blank_chart_news2",
              "cover_page",
              "meows",
              "news2",
              "threshold_4cols",
              "threshold_5cols"
            ],
            "type": "string"
          },
          "type": "array"
        },
        "pages_front": {
          "items": {
            "enum": [
              "blank_chart_meows",
              "blank_chart_news2",
              "cover_page",
              "meows",
              "news2",
              "threshold_4cols",
              "threshold_5cols"
            ],
            "type": "string"
          },
          "type": "array"
        },
        "threshold_4cols": {
          "$ref": "#/definitions/BasePage"
        },
        "threshold_5cols": {
          "$ref": "#/definitions/BasePage"
        }
      },
      "required": [
        "blank_chart_meows",
        "blank_chart_news2",
        "cover_page",
        "font_aliases",
        "meows",
        "news2",
        "page",
        "pages_back_meows",
        "pages_back_news2",
        "pages_front",
        "threshold_4cols",
        "threshold_5cols"
      ],
      "type": "object"
    },
    "Margins": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "bottom": {
          "type": "number"
        },
        "left": {
          "type": "number"
        },
        "right": {
          "type": "number"
        },
        "top": {
          "type": "number"
        }
      },
      "required": [
        "bottom",
        "left",
        "right",
        "top"
      ],
      "type": "object"
    },
    "MessageText": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "bgColour": {
          "type": "string"
        },
        "text": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "Messages": {
      "additionalProperties": {
        "$ref": "#/definitions/MessageText"
      },
      "defaultProperties": [
      ],
      "type": "object"
    },
    "Opt": {
      "$ref": "#/definitions/Opt_1"
    },
    "Opt_1": {
      "additionalProperties": {
      },
      "defaultProperties": [
      ],
      "type": "object"
    },
    "Page": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "margins": {
          "$ref": "#/definitions/Margins"
        },
        "size": {
          "type": "string"
        },
        "translate": {
          "additionalItems": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "number"
              }
            ]
          },
          "items": [
            {
              "type": "number"
            },
            {
              "type": "number"
            }
          ],
          "minItems": 2,
          "type": "array"
        }
      },
      "required": [
        "margins",
        "size",
        "translate"
      ],
      "type": "object"
    },
    "PageName": {
      "enum": [
        "blank_chart_meows",
        "blank_chart_news2",
        "cover_page",
        "meows",
        "news2",
        "threshold_4cols",
        "threshold_5cols"
      ],
      "type": "string"
    },
    "Partial": {
      "$ref": "#/definitions/Partial<Grid>",
      "description": "Make all properties in T optional"
    },
    "Partial<Grid>": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "height": {
          "type": [
            "null",
            "number"
          ]
        },
        "left": {
          "type": "number"
        },
        "show": {
          "type": "boolean"
        },
        "space": {
          "type": "number"
        },
        "top": {
          "type": "number"
        },
        "width": {
          "type": [
            "null",
            "number"
          ]
        }
      },
      "type": "object"
    },
    "Partial<HtmlField>": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "align": {
          "type": "string"
        },
        "caption": {
          "type": [
            "null",
            "string"
          ]
        },
        "captionFont": {
          "type": "string"
        },
        "captionSize": {
          "type": "number"
        },
        "font": {
          "type": "string"
        },
        "fontSize": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "opt": {
          "$ref": "#/definitions/Opt"
        },
        "radius": {
          "type": "number"
        },
        "text": {
          "type": "string"
        },
        "type": {
          "enum": [
            "html"
          ],
          "type": "string"
        },
        "width": {
          "type": "number"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        }
      },
      "type": "object"
    },
    "Partial<HtmlField>_1": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "align": {
          "type": "string"
        },
        "caption": {
          "type": [
            "null",
            "string"
          ]
        },
        "captionFont": {
          "type": "string"
        },
        "captionSize": {
          "type": "number"
        },
        "font": {
          "type": "string"
        },
        "fontSize": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "opt": {
          "$ref": "#/definitions/Opt"
        },
        "radius": {
          "type": "number"
        },
        "text": {
          "type": "string"
        },
        "type": {
          "enum": [
            "html"
          ],
          "type": "string"
        },
        "width": {
          "type": "number"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        }
      },
      "type": "object"
    },
    "Partial<Section>": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "bgColours": {
          "anyOf": [
            {
              "$ref": "#/definitions/BgColours"
            },
            {
              "type": "null"
            }
          ]
        },
        "border": {
          "type": [
            "null",
            "string"
          ]
        },
        "borderWidth": {
          "type": "number"
        },
        "bottom": {
          "type": "number"
        },
        "box": {
          "type": "boolean"
        },
        "candle": {
          "$ref": "#/definitions/Candle"
        },
        "colour": {
          "type": "string"
        },
        "display": {
          "type": [
            "null",
            "string"
          ]
        },
        "font": {
          "type": "string"
        },
        "fontSize": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "high": {
          "type": "number"
        },
        "low": {
          "type": "number"
        },
        "messageBottom": {
          "type": "number"
        },
        "messageTop": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "range": {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "rows": {
          "type": "number"
        },
        "type": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "Partial<SvgField>": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "align": {
          "type": "string"
        },
        "caption": {
          "type": [
            "null",
            "string"
          ]
        },
        "captionFont": {
          "type": "string"
        },
        "captionSize": {
          "type": "number"
        },
        "font": {
          "type": "string"
        },
        "fontSize": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "opt": {
          "$ref": "#/definitions/Opt"
        },
        "radius": {
          "type": "number"
        },
        "text": {
          "type": "string"
        },
        "type": {
          "enum": [
            "svg"
          ],
          "type": "string"
        },
        "width": {
          "type": "number"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        }
      },
      "type": "object"
    },
    "Partial<TableField>": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "align": {
          "type": "string"
        },
        "border": {
          "type": [
            "null",
            "string"
          ]
        },
        "caption": {
          "type": [
            "null",
            "string"
          ]
        },
        "captionFont": {
          "type": "string"
        },
        "captionSize": {
          "type": "number"
        },
        "cellpadding": {
          "type": "number"
        },
        "cells": {
          "items": {
            "items": {
              "anyOf": [
                {
                  "$ref": "#/definitions/Partial<TextField>"
                },
                {
                  "$ref": "#/definitions/Partial<HtmlField>"
                },
                {
                  "type": "string"
                }
              ]
            },
            "type": "array"
          },
          "type": "array"
        },
        "column_names": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "columns": {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "font": {
          "type": "string"
        },
        "fontSize": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "opt": {
          "$ref": "#/definitions/Opt"
        },
        "radius": {
          "type": "number"
        },
        "rowDefaults": {
          "items": {
            "anyOf": [
              {
                "$ref": "#/definitions/Partial<TextField>"
              },
              {
                "$ref": "#/definitions/Partial<HtmlField>"
              }
            ]
          },
          "type": "array"
        },
        "rows": {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "text": {
          "type": "string"
        },
        "type": {
          "enum": [
            "table"
          ],
          "type": "string"
        },
        "width": {
          "type": "number"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        }
      },
      "type": "object"
    },
    "Partial<TextField>": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "align": {
          "type": "string"
        },
        "caption": {
          "type": [
            "null",
            "string"
          ]
        },
        "captionFont": {
          "type": "string"
        },
        "captionSize": {
          "type": "number"
        },
        "font": {
          "type": "string"
        },
        "fontSize": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "opt": {
          "$ref": "#/definitions/Opt"
        },
        "radius": {
          "type": "number"
        },
        "text": {
          "type": "string"
        },
        "type": {
          "enum": [
            "",
            "text"
          ],
          "type": "string"
        },
        "width": {
          "type": "number"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        }
      },
      "type": "object"
    },
    "Partial<TextField>_1": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "align": {
          "type": "string"
        },
        "caption": {
          "type": [
            "null",
            "string"
          ]
        },
        "captionFont": {
          "type": "string"
        },
        "captionSize": {
          "type": "number"
        },
        "font": {
          "type": "string"
        },
        "fontSize": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "opt": {
          "$ref": "#/definitions/Opt"
        },
        "radius": {
          "type": "number"
        },
        "text": {
          "type": "string"
        },
        "type": {
          "enum": [
            "",
            "text"
          ],
          "type": "string"
        },
        "width": {
          "type": "number"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        }
      },
      "type": "object"
    },
    "Section": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "bgColours": {
          "anyOf": [
            {
              "$ref": "#/definitions/BgColours"
            },
            {
              "type": "null"
            }
          ]
        },
        "border": {
          "type": [
            "null",
            "string"
          ]
        },
        "borderWidth": {
          "type": "number"
        },
        "bottom": {
          "type": "number"
        },
        "box": {
          "type": "boolean"
        },
        "candle": {
          "$ref": "#/definitions/Candle"
        },
        "colour": {
          "type": "string"
        },
        "display": {
          "type": [
            "null",
            "string"
          ]
        },
        "font": {
          "type": "string"
        },
        "fontSize": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "high": {
          "type": "number"
        },
        "low": {
          "type": "number"
        },
        "messageBottom": {
          "type": "number"
        },
        "messageTop": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "range": {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "rows": {
          "type": "number"
        },
        "type": {
          "type": "string"
        }
      },
      "required": [
        "bgColours",
        "border",
        "borderWidth",
        "bottom",
        "box",
        "colour",
        "display",
        "font",
        "fontSize",
        "height",
        "high",
        "low",
        "name",
        "range",
        "rows",
        "type"
      ],
      "type": "object"
    },
    "SvgField": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "align": {
          "type": "string"
        },
        "caption": {
          "type": [
            "null",
            "string"
          ]
        },
        "captionFont": {
          "type": "string"
        },
        "captionSize": {
          "type": "number"
        },
        "font": {
          "type": "string"
        },
        "fontSize": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "opt": {
          "$ref": "#/definitions/Opt"
        },
        "radius": {
          "type": "number"
        },
        "text": {
          "type": "string"
        },
        "type": {
          "enum": [
            "svg"
          ],
          "type": "string"
        },
        "width": {
          "type": "number"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        }
      },
      "required": [
        "caption",
        "captionFont",
        "captionSize",
        "font",
        "fontSize",
        "height",
        "name",
        "radius",
        "text",
        "type",
        "width",
        "x",
        "y"
      ],
      "type": "object"
    },
    "TableCell": {
      "anyOf": [
        {
          "$ref": "#/definitions/Partial<TextField>"
        },
        {
          "$ref": "#/definitions/Partial<HtmlField>"
        },
        {
          "type": "string"
        }
      ]
    },
    "TableField": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "align": {
          "type": "string"
        },
        "border": {
          "type": [
            "null",
            "string"
          ]
        },
        "caption": {
          "type": [
            "null",
            "string"
          ]
        },
        "captionFont": {
          "type": "string"
        },
        "captionSize": {
          "type": "number"
        },
        "cellpadding": {
          "type": "number"
        },
        "cells": {
          "items": {
            "items": {
              "anyOf": [
                {
                  "$ref": "#/definitions/Partial<TextField>"
                },
                {
                  "$ref": "#/definitions/Partial<HtmlField>"
                },
                {
                  "type": "string"
                }
              ]
            },
            "type": "array"
          },
          "type": "array"
        },
        "column_names": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "columns": {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "font": {
          "type": "string"
        },
        "fontSize": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "opt": {
          "$ref": "#/definitions/Opt"
        },
        "radius": {
          "type": "number"
        },
        "rowDefaults": {
          "items": {
            "anyOf": [
              {
                "$ref": "#/definitions/Partial<TextField>"
              },
              {
                "$ref": "#/definitions/Partial<HtmlField>"
              }
            ]
          },
          "type": "array"
        },
        "rows": {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "text": {
          "type": "string"
        },
        "type": {
          "enum": [
            "table"
          ],
          "type": "string"
        },
        "width": {
          "type": "number"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        }
      },
      "required": [
        "border",
        "caption",
        "captionFont",
        "captionSize",
        "cellpadding",
        "cells",
        "column_names",
        "columns",
        "font",
        "fontSize",
        "height",
        "name",
        "radius",
        "rowDefaults",
        "rows",
        "text",
        "type",
        "width",
        "x",
        "y"
      ],
      "type": "object"
    },
    "TextField": {
      "additionalProperties": false,
      "defaultProperties": [
      ],
      "properties": {
        "align": {
          "type": "string"
        },
        "caption": {
          "type": [
            "null",
            "string"
          ]
        },
        "captionFont": {
          "type": "string"
        },
        "captionSize": {
          "type": "number"
        },
        "font": {
          "type": "string"
        },
        "fontSize": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "opt": {
          "$ref": "#/definitions/Opt"
        },
        "radius": {
          "type": "number"
        },
        "text": {
          "type": "string"
        },
        "type": {
          "enum": [
            "",
            "text"
          ],
          "type": "string"
        },
        "width": {
          "type": "number"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        }
      },
      "required": [
        "caption",
        "captionFont",
        "captionSize",
        "font",
        "fontSize",
        "height",
        "name",
        "radius",
        "text",
        "type",
        "width",
        "x",
        "y"
      ],
      "type": "object"
    }
  }
};
ajv.addSchema(Schema, 'Schema')
export function validate(typeName: 'Margins'): (value: unknown) => Margins;
export function validate(typeName: 'Page'): (value: unknown) => Page;
export function validate(typeName: 'FontAliases'): (value: unknown) => FontAliases;
export function validate(typeName: 'Grid'): (value: unknown) => Grid;
export function validate(typeName: 'Opt'): (value: unknown) => Opt;
export function validate(typeName: 'FieldBase'): (value: unknown) => FieldBase;
export function validate(typeName: 'TextField'): (value: unknown) => TextField;
export function validate(typeName: 'HtmlField'): (value: unknown) => HtmlField;
export function validate(typeName: 'SvgField'): (value: unknown) => SvgField;
export function validate(typeName: 'TableCell'): (value: unknown) => TableCell;
export function validate(typeName: 'TableField'): (value: unknown) => TableField;
export function validate(typeName: 'Field'): (value: unknown) => Field;
export function validate(typeName: 'BasePage'): (value: unknown) => BasePage;
export function validate(typeName: 'MessageText'): (value: unknown) => MessageText;
export function validate(typeName: 'Messages'): (value: unknown) => Messages;
export function validate(typeName: 'ConsciousnessMap'): (value: unknown) => ConsciousnessMap;
export function validate(typeName: 'Column'): (value: unknown) => Column;
export function validate(typeName: 'BgColours'): (value: unknown) => BgColours;
export function validate(typeName: 'Candle'): (value: unknown) => Candle;
export function validate(typeName: 'Section'): (value: unknown) => Section;
export function validate(typeName: 'ChartPage'): (value: unknown) => ChartPage;
export function validate(typeName: 'PageName'): (value: unknown) => PageName;
export function validate(typeName: 'LayoutConfig'): (value: unknown) => LayoutConfig;
export function validate(typeName: string): (value: unknown) => any {
  const validator: any = ajv.getSchema(`Schema#/definitions/${typeName}`);
  return (value: unknown): any => {
    if (!validator) {
      throw new Error(`No validator defined for Schema#/definitions/${typeName}`)
    }
  
    const valid = validator(value);

    if (!valid) {
      throw new Error(
        'Invalid ' + typeName + ': ' + ajv.errorsText(validator.errors, {dataVar: typeName}),
      );
    }

    return value as any;
  };
}